# Generated by Django 2.0 on 2018-09-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
